server:
  port: 8081

spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: example
      database: products
      port: 27017
      host: localhost
      auto-index-creation: true
      uuid-representation: standard
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

aga:
  repository:
    implementation: mongo